config:
  credentials:
  - id: synergy_dockerhub_bot_pass
    password_var: JPL_DOCKERPASS
    username_var: JPL_DOCKERUSER
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
environment:
  JPL_DOCKERPUSH: o3asapi
sqa_criteria:
  qc_functional:
    repos:
      this_repo:
        commands:
        - echo 'building docker image for o3as api..'
        container: o3asapi
timeout: 600
