config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/o3api:
      branch: master
      repo: https://github.com/EOSC-synergy/o3api
environment: {}
sqa_criteria:
  qc_style:
    repos:
      this_repo:
        container: o3asapi-testing
        tox:
          testenv:
          - ALL
          tox_file: ./tox.ini
timeout: 600
